In [1]:
import pandas as pd
import numpy as np

In [3]:
date=pd.read_csv("orders.csv")
time=pd.read_csv("messages.csv")

In [12]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [11]:
date["date"]=pd.to_datetime(date["date"])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#1.Extract Year

In [32]:
date["date_year"]=date["date"].dt.year
date.head(5)

        date  product_id  city_id  orders date_month_no  date_year
0 2019-12-10        5628       25       3      December       2019
1 2018-08-15        3646       14     157        August       2018
2 2018-10-23        1859       25       1       October       2018
3 2019-08-17        7292       25       1        August       2019
4 2019-01-06        4344       25       3       January       2019

#Extract Month

In [31]:
date["date_month_no"]=date["date"].dt.month #for number
date["date_month_no"]=date["date"].dt.month_name() #for name


date.head()

        date  product_id  city_id  orders date_month_no  date_year
0 2019-12-10        5628       25       3      December       2019
1 2018-08-15        3646       14     157        August       2018
2 2018-10-23        1859       25       1       October       2018
3 2019-08-17        7292       25       1        August       2019
4 2019-01-06        4344       25       3       January       2019

#Extract Days

In [35]:
date["Day"]=date["date"].dt.day_name()
date.head()

        date  product_id  city_id  orders date_month_no  date_year        Day
0 2019-12-10        5628       25       3      December       2019    Tuesday
1 2018-08-15        3646       14     157        August       2018  Wednesday
2 2018-10-23        1859       25       1       October       2018    Tuesday
3 2019-08-17        7292       25       1        August       2019   Saturday
4 2019-01-06        4344       25       3       January       2019     Sunday

In [13]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

# Is weekend

In [43]:
date["Is_weekend"]=np.where(date["Day"].isin(["Sunday","Saturday"]),True,False)
date.head()

,date,product_id,city_id,orders,date_month_no,date_year,Day,Is_weekend
0,2019-12-10,5628,25,3,December,2019,Tuesday,False
1,2018-08-15,3646,14,157,August,2018,Wednesday,False
2,2018-10-23,1859,25,1,October,2018,Tuesday,False
3,2019-08-17,7292,25,1,August,2019,Saturday,True
4,2019-01-06,4344,25,3,January,2019,Sunday,True

# Time

In [15]:
time["date"]=pd.to_datetime(time["date"])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [44]:
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [46]:
time["Hours"]=time["date"].dt.hour
time["Minutes"]=time["date"].dt.minute
time["Seconds"]=time["date"].dt.second
time.head()

,date,msg,Hours,Minutes,Seconds
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

# Extract only time & Date

In [48]:
time["Time"]=time["date"].dt.time
time["Date"]=time["date"].dt.date
time.head()

,date,msg,Hours,Minutes,Seconds,Time,Date
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00,2013-12-15
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00,2014-04-29
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00,2012-12-30
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00,2014-11-28
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00,2013-10-26

In [75]:
import datetime
today=datetime.datetime.today()
time["Diff"]=(today- time['date']).dt.days
time.head()

,date,msg,Hours,Minutes,Seconds,Time,Date,Diff
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00,2013-12-15,4653
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00,2014-04-29,4517
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00,2012-12-30,5003
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00,2014-11-28,4305
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00,2013-10-26,4702